### ISSUE TITLE
Please help me，Solve this bug ,  Openbci : Cyton with WiFi Shield

### ISSUE THREAD

**Issue by lomoao** [Andrey1994/brainflow#27]
(tensorflow-gpu) D:\PycharmProjects\openbci\python_tests>python brainflow_get_data.py --ip-address 192.168.4.1 --board-id 5
Traceback (most recent call last):
  File "brainflow_get_data.py", line 54, in <module>
    main ()
  File "brainflow_get_data.py", line 39, in main
    board.prepare_session ()
  File "C:\Users\Administrator\.conda\envs\tensorflow-gpu\lib\site-packages\brainflow\board_shim.py", line 722,
 in prepare_session
    raise BrainFlowError ('unable to prepare streaming session', res)
brainflow.board_shim.BrainFlowError: INVALID_ARGUMENTS_ERROR:13 unable to prepare streaming session

**Comment by Andrey1994** [comment]
We have issue format https://brainflow.readthedocs.io/en/stable/AskHelp.html#issue-format which helps to solve problems
Also if you rerun it with logger you will see what the issue is.

According to https://brainflow.readthedocs.io/en/stable/SupportedBoards.html ip-port field is required for wifi shield boards
